module SolidusJwt
  module Decodeable
    ##
    # Decode a token generated by SolidusJwt
    # @see https://github.com/jwt/ruby-jwt
    #
    # @param token [String] The token to decode
    # @return [Array<Hash>]
    #
    def decode(token)
      JWT.decode(token, SolidusJwt::Config.jwt_secret, true,
        algorithm: SolidusJwt::Config.jwt_algorithm)
    end
  end
end
